<%@ Page Language="C#" AutoEventWireup="true" CodeFile="FileList.aspx.cs" Inherits="FileList" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        <asp:Button ID="UpLoadBtn" runat="server" Text="上传文件" Width="80" Height="30" 
            onclick="UpLoadBtn_Click" />
        <asp:Button ID="DownLoadBtn" runat="server" Text="下载文件" Width="80" Height="30" 
            onclick="DownLoadBtn_Click" />
        <asp:Button ID="NewDirBtn" runat="server" Text="新建目录" Width="80" Height="30" 
            onclick="NewDirBtn_Click" />
        <asp:Button ID="UpdateNameBtn" runat="server" Text="修改此项" Width="80" 
            Height="30" onclick="UpdateNameBtn_Click" />
        <asp:Button ID="DeleteBtn" runat="server" Text="删除此项" Width="80" Height="30" 
            onclick="DeleteBtn_Click" />
        <asp:TreeView ID="FileListView" runat="server" Width="100%" ShowLines="true" BackColor="#5a7dd1" ForeColor="White" AutoGenerateDataBindings="false" EnableClientScript="false"  >
        <NodeStyle BackColor="#5a7dd1" ForeColor="Wheat" Font-Bold="true" />
        <RootNodeStyle BackColor="Transparent" Font-Bold="true" ForeColor="White" />
        <SelectedNodeStyle BackColor="#5a7dd1" ForeColor="OrangeRed"  Font-Bold="true" />
        </asp:TreeView>

    </div>
    </form>
</body>
</html>
