// mock 放到此处，被 根目录 mock 文件夹引用，可在本地正常启动 umi dev
// 同时在 build 时，可在 github gh-pages 使用此处静态数据。

const graphDetail = {
  creator: "070186",
  creatorName: "华雷",
  id: 1,
  name: "Web 技术",
  description: "Web 技术",
  fileKey: "file/design/xxx.txt",
  fileString: null,
  gmtCreate: "2020-08-07T15:18:35.000+0000",
  gmtModified: "2020-08-07T15:18:35.000+0000",
  modifier: "070186",
  modifierName: "华雷",
  open: true,
  own: true,
  tagNames: null,
  tagVOList: [],
  totalPv: 4,
  typeKey: "fast",
  typeName: "快速架构图",
  version: 9,
  xmlText:
  "<mxGraphModel><root><mxCell id=\"0\" value=\"技术架构图\"/><mxCell id=\"1\" value=\"默认图层\" parent=\"0\"/><mxCell id=\"2\" value=\"\" style=\"shape=swimlane;startSize=0;fillColor=none;strokeColor=none;\" parent=\"1\" vertex=\"1\" connectable=\"0\" _hor=\"1\" _col=\"2\" _pos=\"10\"><mxGeometry x=\"10\" y=\"10\" width=\"955\" height=\"30\" as=\"geometry\"/></mxCell><mxCell id=\"3\" value=\"填写标题\" style=\"shape=label;perimeter=rectanglePerimeter;align=center;verticalAlign=middle;overflow=hidden;imageAlign=left;imageVerticalAlign=middle;imageWidth=20;imageHeight=20;fontSize=14;fillColor=#73777a;strokeColor=#73777a;fontColor=#ffffff;bold=1;spacingLeft=0;spacing=0;\" parent=\"2\" vertex=\"1\" _tit=\"1\"><mxGeometry width=\"80\" height=\"30\" as=\"geometry\"/></mxCell><mxCell id=\"4\" value=\"\" style=\"shape=swimlane;startSize=0;fillColor=none;strokeColor=none;\" parent=\"2\" vertex=\"1\" connectable=\"0\" _hor=\"2\" _col=\"1\" _pos=\"1\"><mxGeometry x=\"90\" width=\"865\" height=\"30\" as=\"geometry\"/></mxCell><mxCell id=\"5\" value=\"\" style=\"shape=swimlane;startSize=0;fillColor=none;strokeColor=none;\" parent=\"4\" vertex=\"1\" connectable=\"0\" _hor=\"1\" _col=\"8\" _pos=\"2\"><mxGeometry width=\"865\" height=\"30\" as=\"geometry\"/></mxCell><mxCell id=\"6\" value=\"React.js\" style=\"shape=label;perimeter=rectanglePerimeter;align=left;verticalAlign=middle;overflow=hidden;imageAlign=left;imageVerticalAlign=middle;imageWidth=20;imageHeight=20;fontSize=12;fillColor=#ffffff;strokeColor=#181818;fontColor=#000;spacingLeft=30;spacing=390.82421875;image=https://img.alicdn.com/tfs/TB1mkHhgfzO3e4jSZFxXXaP_FXa-186-186.png;\" parent=\"5\" vertex=\"1\" _mid=\"297\"><mxGeometry width=\"865\" height=\"30\" as=\"geometry\"/></mxCell></root></mxGraphModel>",
  xml: "<mxgraphmodel><root width=\"989\" height=\"563\"><mxcell shapeid=\"-1\" value=\"未命名\" position=\"{&quot;x&quot;:0,&quot;y&quot;:5,&quot;width&quot;:955,&quot;height&quot;:30}\" style=\"{&quot;shape&quot;:&quot;swimlane&quot;,&quot;verticalAlign&quot;:&quot;middle&quot;,&quot;align&quot;:&quot;center&quot;,&quot;fontColor&quot;:&quot;#774400&quot;,&quot;startSize&quot;:0,&quot;shapeNum&quot;:5,&quot;title&quot;:true,&quot;fontBold&quot;:true,&quot;fontSize&quot;:20}\"></mxcell><mxcell value=\"\" position=\"{&quot;x&quot;:10,&quot;y&quot;:50,&quot;width&quot;:955,&quot;height&quot;:30}\" style=\"{&quot;shape&quot;:&quot;swimlane&quot;,&quot;verticalAlign&quot;:&quot;middle&quot;,&quot;align&quot;:&quot;center&quot;,&quot;fontColor&quot;:&quot;#774400&quot;,&quot;startSize&quot;:0,&quot;shapeNum&quot;:5}\" shapeid=\"2\" parentshapeid=\"1\" metadataname=\"\"></mxcell><mxcell value=\"填写标题\" position=\"{&quot;x&quot;:0,&quot;y&quot;:0,&quot;width&quot;:80,&quot;height&quot;:30}\" style=\"{&quot;shape&quot;:&quot;label&quot;,&quot;perimeter&quot;:&quot;rectanglePerimeter&quot;,&quot;verticalAlign&quot;:&quot;middle&quot;,&quot;align&quot;:&quot;center&quot;,&quot;fillColor&quot;:&quot;#73777a&quot;,&quot;strokeColor&quot;:&quot;#73777a&quot;,&quot;fontColor&quot;:&quot;#ffffff&quot;,&quot;overflow&quot;:&quot;hidden&quot;,&quot;imageAlign&quot;:&quot;left&quot;,&quot;imageVerticalAlign&quot;:&quot;middle&quot;,&quot;imageWidth&quot;:20,&quot;imageHeight&quot;:20,&quot;fontSize&quot;:14,&quot;bold&quot;:1,&quot;spacingLeft&quot;:0,&quot;spacing&quot;:0,&quot;shapeNum&quot;:5}\" shapeid=\"3\" parentshapeid=\"2\" metadataname=\"填写标题\"></mxcell><mxcell value=\"\" position=\"{&quot;x&quot;:90,&quot;y&quot;:0,&quot;width&quot;:865,&quot;height&quot;:30}\" style=\"{&quot;shape&quot;:&quot;swimlane&quot;,&quot;verticalAlign&quot;:&quot;middle&quot;,&quot;align&quot;:&quot;center&quot;,&quot;fontColor&quot;:&quot;#774400&quot;,&quot;startSize&quot;:0,&quot;shapeNum&quot;:5}\" shapeid=\"4\" parentshapeid=\"2\" metadataname=\"\"></mxcell><mxcell value=\"\" position=\"{&quot;x&quot;:0,&quot;y&quot;:0,&quot;width&quot;:865,&quot;height&quot;:30}\" style=\"{&quot;shape&quot;:&quot;swimlane&quot;,&quot;verticalAlign&quot;:&quot;middle&quot;,&quot;align&quot;:&quot;center&quot;,&quot;fontColor&quot;:&quot;#774400&quot;,&quot;startSize&quot;:0,&quot;shapeNum&quot;:5}\" shapeid=\"5\" parentshapeid=\"4\" metadataname=\"\"></mxcell><mxcell value=\"React.js\" position=\"{&quot;x&quot;:0,&quot;y&quot;:0,&quot;width&quot;:865,&quot;height&quot;:30}\" style=\"{&quot;shape&quot;:&quot;label&quot;,&quot;perimeter&quot;:&quot;rectanglePerimeter&quot;,&quot;verticalAlign&quot;:&quot;middle&quot;,&quot;align&quot;:&quot;left&quot;,&quot;fillColor&quot;:&quot;#ffffff&quot;,&quot;strokeColor&quot;:&quot;#181818&quot;,&quot;fontColor&quot;:&quot;#000&quot;,&quot;overflow&quot;:&quot;hidden&quot;,&quot;imageAlign&quot;:&quot;left&quot;,&quot;imageVerticalAlign&quot;:&quot;middle&quot;,&quot;imageWidth&quot;:20,&quot;imageHeight&quot;:20,&quot;fontSize&quot;:12,&quot;spacingLeft&quot;:30,&quot;spacing&quot;:390.82421875,&quot;image&quot;:&quot;https://img.alicdn.com/tfs/TB1mkHhgfzO3e4jSZFxXXaP_FXa-186-186.png&quot;,&quot;shapeNum&quot;:5}\" shapeid=\"6\" parentshapeid=\"5\" metadataname=\"React.js\" icon=\"{&quot;width&quot;:20,&quot;height&quot;:20,&quot;iconUrl&quot;:&quot;https://img.alicdn.com/tfs/TB1mkHhgfzO3e4jSZFxXXaP_FXa-186-186.png&quot;,&quot;x&quot;:390.82421875,&quot;y&quot;:5}\" metadataid=\"297\"></mxcell></root></mxgraphmodel>",
};

const graphList = {
  success: true,
  data: {
    current: 1,
    size: 1,
    total: 1,
    records: [graphDetail],
  },
};
const postRes = {
  requestId: "e7744d64-ac6e-492c-9188-3f34493649b1",
  code: "200",
  message: "success",
  success: true,
  data: true,
};

export default {
  // GET 前缀默认可忽略
  "/4A/getLoginUrl": { success: true, data: { loginUrl: "xxx" } },
  "/account/user/info": { success: true, data: { accountId: 222 } },
  "/project/api/project/instance/getByInstanceId": {
    requestId: "69f96436-ab41-4acb-ae03-b6338f50da2a",
    code: "",
    message: "success",
    success: true,
    data: [],
  },
  "/platform/api/business/summary": {
    requestId: "021862a6-f07c-4556-8967-2144957ee081",
    code: "",
    message: "success",
    success: true,
    meta: null,
    data: {
      total: 86,
      list: [
        {
          projectId: 46560520,
          projectName: "交付项目主需求池",
          collection: false,
        },
        {
          projectId: 46563229,
          projectName: "GTS统一工作台-工作日志（周日报）",
          collection: false,
        },
        {
          projectId: 3491,
          projectName: "【用户反馈需求池-待用反上线后接入】大禹",
          collection: false,
        },
        {
          projectId: 46536011,
          projectName: "软通专属钉钉",
          collection: true,
        },
        {
          projectId: 46541438,
          projectName: "大禹",
          collection: true,
        },
      ],
      pageNum: 1,
      pageSize: 5,
      size: 0,
    },
  },
  "/platform/api/business/projectCollections/46541438/relatedProjects": {
    requestId: "fc1e594d-0d7c-4aa4-91d4-306f663d45ed",
    code: "",
    message: "success",
    success: true,
    data: {
      total: 16,
      list: [
        {
          projectId: 46563229,
          projectName: "GTS统一工作台-工作日志（周日报）",
          collection: null,
        },
        {
          projectId: 3491,
          projectName: "【用户反馈需求池-待用反上线后接入】大禹",
          collection: null,
        },
        {
          projectId: 46532231,
          projectName: "项目平台管理",
          collection: null,
        },
      ],
      pageNum: 1,
      pageSize: 100,
      size: 0,
    },
  },
  "/platform/api/business/projectCollections/46536011/relatedProjects": {
    requestId: "2fbb9252-4081-4783-b4b8-1fbfd0f9c3b7",
    code: "",
    message: "success",
    success: true,
    meta: null,
    data: {
      total: 2,
      list: [
        {
          projectId: 46532063,
          projectName: "软通专属钉钉",
          collection: null,
        },
        {
          projectId: 46591470,
          projectName: "客户服务信息[勿删]",
          collection: null,
        },
      ],
      pageNum: 1,
      pageSize: 100,
      size: 0,
    },
  },
  "/design/tag/page/list/get": {
    requestId: "a3c92a24-5dbd-4ba9-b62e-4e592084db50",
    code: "200",
    message: "success",
    success: true,
    meta: null,
    data: {
      total: 23,
      current: 1,
      size: 20,
      records: [
        { name: "Web前端", id: 68 },
        { name: "Web前端", id: 69 },
        { name: "未分类", id: 70 },
        { name: "数据中台", id: 71 },
        { name: "两级贯通", id: 72 },
        { name: "A", id: 73 },
        { name: "A", id: 74 },
        { name: "架构图打标测试1", id: 75 },
        { name: "架构图打标测试2", id: 76 },
        { name: "数据中台架构", id: 77 },
        { name: "数字警卫", id: 164 },
        { name: "重点车", id: 165 },
        { name: "一键护航", id: 166 },
        { name: "北京交管", id: 167 },
        { name: "专题库", id: 168 },
        { name: "教育", id: 169 },
        { name: "西安最多跑一次", id: 170 },
        { name: "数据中台整体业务架构", id: 171 },
        { name: "数据中台及服务架构", id: 172 },
        { name: "gov-algorithm", id: 173 },
      ],
    },
    traceId: "2f624a7616428245826876020e273a",
    empty: false,
  },
  "/design/instance/id/get/detail": {
    success: true,
    data: graphDetail,
  },
  "/design/template/id/get/detail": {
    success: true,
    data: graphDetail,
  },
  "/design/instance/page/list/get": graphList,
  "/design/template/page/list/get": graphList,
  "/design/instance/open/page/list/get": graphList,
  "/design/template/open/page/list/get": graphList,
  "/design/ppt/export": (req, res) => {
    const resBody = '';
    res.end(resBody);
    return resBody;
  },
  "POST /oss/design/uploadFile": {
    requestId: "cbc9e80c-f727-414c-b646-03be6fd407d8",
    code: "200",
    message: "success",
    success: true,
    meta: null,
    data: "https://dayu-icon-prd.oss-cn-zhangjiakou.aliyuncs.com/icon/TB1dy.LQBr0gK0jSZFnXXbRRXXa-96-961642833566207.png",
    traceId: "2f624a7616428335660794705e273d",
    empty: false,
  },
  "/oss/inline/txt": (req, res) => {
    const resBody = '<svg style="left: 0px; top: 0px; width: 100%; height: 100%; display: block;" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 985 557"><g transform="translate(1,1)"><g></g><g><g transform="translate(0.5,0.5)" style="visibility: visible;"><path d="M 10 10 L 10 10 L 965 10 L 965 10" fill="none" stroke="white" pointer-events="stroke" visibility="hidden" stroke-width="9"></path><path d="M 10 10 L 10 10 L 965 10 L 965 10" fill="none" stroke="none" pointer-events="all"></path><path d="M 10 10 L 10 40 L 965 40 L 965 10" fill="none" stroke="white" pointer-events="stroke" visibility="hidden" stroke-width="9"></path><path d="M 10 10 L 965 10" fill="none" stroke="white" pointer-events="stroke" visibility="hidden" stroke-width="9"></path></g><g transform="translate(0.5,0.5)" style="visibility: visible;"><rect x="10" y="10" width="80" height="30" fill="#73777a" stroke="#73777a" pointer-events="all"></rect></g><g style=""><clipPath id="mx-clip-8-8-84-34-0"><rect x="8" y="8" width="84" height="34"></rect></clipPath><g fill="#ffffff" font-family="Arial,Helvetica" clip-path="url(https://tfox.gts.work/editor?id=8067#mx-clip-8-8-84-34-0)" text-anchor="middle" font-size="14px"><text x="50" y="31">å¡«å†™æ ‡é¢˜</text></g></g><g transform="translate(0.5,0.5)" style="visibility: visible;"><path d="M 100 10 L 100 10 L 965 10 L 965 10" fill="none" stroke="white" pointer-events="stroke" visibility="hidden" stroke-width="9"></path><path d="M 100 10 L 100 10 L 965 10 L 965 10" fill="none" stroke="none" pointer-events="all"></path><path d="M 100 10 L 100 40 L 965 40 L 965 10" fill="none" stroke="white" pointer-events="stroke" visibility="hidden" stroke-width="9"></path><path d="M 100 10 L 965 10" fill="none" stroke="white" pointer-events="stroke" visibility="hidden" stroke-width="9"></path></g><g transform="translate(0.5,0.5)" style="visibility: visible;"><path d="M 100 10 L 100 10 L 965 10 L 965 10" fill="none" stroke="white" pointer-events="stroke" visibility="hidden" stroke-width="9"></path><path d="M 100 10 L 100 10 L 965 10 L 965 10" fill="none" stroke="none" pointer-events="all"></path><path d="M 100 10 L 100 40 L 965 40 L 965 10" fill="none" stroke="white" pointer-events="stroke" visibility="hidden" stroke-width="9"></path><path d="M 100 10 L 965 10" fill="none" stroke="white" pointer-events="stroke" visibility="hidden" stroke-width="9"></path></g><g transform="translate(0.5,0.5)" style="visibility: visible;"><rect x="100" y="10" width="865" height="30" fill="#ffffff" stroke="#181818" pointer-events="all"></rect><image x="495.82" y="15" width="20" height="20" xlink:href="https://img.alicdn.com/tfs/TB1mkHhgfzO3e4jSZFxXXaP_FXa-186-186.png" preserveAspectRatio="none"></image></g><g style=""><g fill="#000" font-family="Arial,Helvetica" font-size="12px"><text x="520" y="30">React.js</text></g></g></g><g></g><g></g></g></svg>';
    res.end(resBody);
    return resBody;
  },
  "/design/metadata/node/get": {
    requestId: "3237f2d5-10b8-4463-82aa-75153cbe8395",
    code: "200",
    message: "success",
    success: true,
    meta: null,
    data: {
      metadataVOList: [
        {
          metadataId: 297,
          metadataName: "React.js",
          metadataSortNum: 1,
          metadataIconUrl:
            "https://img.alicdn.com/tfs/TB1mkHhgfzO3e4jSZFxXXaP_FXa-186-186.png",
          metadataOfficialWebsite: "https://reactjs.org/",
          source: "local",
        },
        {
          metadataId: 298,
          metadataName: "Vue.js",
          metadataSortNum: 2,
          metadataIconUrl:
            "https://img.alicdn.com/tfs/TB1wbUHQxv1gK0jSZFFXXb0sXXa-400-400.png",
          metadataOfficialWebsite: "https://vuejs.org/",
          source: "local",
        },
      ],
      categoryVOList: [
        { categoryId: 162, categoryName: "阿里云" },
        { categoryId: 163, categoryName: "开源技术体系" },
      ],
    },
    traceId: "2f624a7616428269315841819e2744",
    empty: false,
  },
  "/design/metadata/page/list/get": {
    requestId: "97469388-a424-4e79-82b3-920de6e6577f",
    code: "200",
    message: "success",
    success: true,
    meta: null,
    data: {
      total: 843,
      current: 1,
      size: 4,
      records: [
        {
          id: 855,
          code: "subcontract",
          cnName: null,
          enName: "Subcontract-Service",
          firstCategoryId: 162,
          firstCategoryName: "阿里云",
          secondCategoryId: null,
          secondCategoryName: null,
          thirdCategoryId: null,
          thirdCategoryName: null,
          shortDescription: "非标三方服务",
          longDescription: null,
          introduction: null,
          gmtCreate: "2022-01-20T09:00:01.000+0000",
          gmtModified: "2022-01-21T09:00:01.000+0000",
          creator: null,
          modifier: null,
          creatorName: null,
          modifierName: null,
          isDeleted: "n",
          tagVOList: null,
          sortNum: null,
          iconUrl: null,
          iconId: null,
          iconName: null,
          typeKey: null,
          typeValue: null,
          source: "cloud",
          officialWebsite: null,
        },
        {
          id: 854,
          code: "cnstack",
          cnName: null,
          enName: "CNStack",
          firstCategoryId: 162,
          firstCategoryName: "阿里云",
          secondCategoryId: 84,
          secondCategoryName: "基础产品事业部",
          thirdCategoryId: 838,
          thirdCategoryName: "互联网中间件",
          shortDescription: "云原生Stack",
          longDescription: null,
          introduction: null,
          gmtCreate: "2022-01-20T09:00:01.000+0000",
          gmtModified: "2022-01-21T09:00:01.000+0000",
          creator: null,
          modifier: null,
          creatorName: null,
          modifierName: null,
          isDeleted: "n",
          tagVOList: null,
          sortNum: null,
          iconUrl: null,
          iconId: null,
          iconName: null,
          typeKey: null,
          typeValue: null,
          source: "cloud",
          officialWebsite: null,
        },
        {
          id: 853,
          code: "jfrog",
          cnName: null,
          enName: null,
          firstCategoryId: 162,
          firstCategoryName: "阿里云",
          secondCategoryId: null,
          secondCategoryName: null,
          thirdCategoryId: null,
          thirdCategoryName: null,
          shortDescription: "Jfrog",
          longDescription: null,
          introduction: null,
          gmtCreate: "2022-01-18T09:00:01.000+0000",
          gmtModified: "2022-01-21T09:00:01.000+0000",
          creator: null,
          modifier: null,
          creatorName: null,
          modifierName: null,
          isDeleted: "n",
          tagVOList: null,
          sortNum: null,
          iconUrl: null,
          iconId: null,
          iconName: null,
          typeKey: null,
          typeValue: null,
          source: "cloud",
          officialWebsite: null,
        },
        {
          id: 852,
          code: "wtc",
          cnName: null,
          enName: "Alibaba Cloud Workspace Thin Client",
          firstCategoryId: 162,
          firstCategoryName: "阿里云",
          secondCategoryId: 79,
          secondCategoryName: "云计算基础",
          thirdCategoryId: null,
          thirdCategoryName: null,
          shortDescription: "无影客户端",
          longDescription: null,
          introduction: null,
          gmtCreate: "2022-01-11T09:00:01.000+0000",
          gmtModified: "2022-01-21T09:00:01.000+0000",
          creator: null,
          modifier: null,
          creatorName: null,
          modifierName: null,
          isDeleted: "n",
          tagVOList: null,
          sortNum: null,
          iconUrl: null,
          iconId: null,
          iconName: null,
          typeKey: null,
          typeValue: null,
          source: "cloud",
          officialWebsite: null,
        },
      ],
    },
    traceId: "2f624a7616428309953085318e2740",
    empty: false,
  },
  "/design/icon/page/list/get": {
    requestId: "c3b26561-4d0d-41c4-8ba3-878465a911ca",
    code: "200",
    message: "success",
    success: true,
    meta: null,
    data: {
      total: 236,
      current: 1,
      size: 3,
      records: [
        {
          id: 236,
          name: "mse 微服务引擎.png",
          url: "https://dayu-icon-prd.oss-cn-zhangjiakou.aliyuncs.com/icon/mse 微服务引擎1598013975370.png",
          source: "sync",
          tagVOS: [
            { sourceCode: null, pid: 236, tagId: 61, tagName: "架构图icon" },
            { sourceCode: null, pid: 236, tagId: 55, tagName: "2D" },
            { sourceCode: null, pid: 236, tagId: 61, tagName: "架构图icon" },
            { sourceCode: null, pid: 236, tagId: 62, tagName: "企业应用" },
            { sourceCode: null, pid: 236, tagId: 50, tagName: "图标" },
            { sourceCode: null, pid: 236, tagId: 59, tagName: "无人" },
          ],
          gmtCreate: "2020-08-21T12:45:56.000+0000",
          gmtModified: "2020-08-21T12:46:47.000+0000",
          creator: "5941",
          modifier: "5941",
          creatorName: "cxl",
          modifierName: "cxl",
          isDeleted: "n",
        },
        {
          id: 235,
          name: "企业建站.png",
          url: "https://dayu-icon-prd.oss-cn-zhangjiakou.aliyuncs.com/icon/企业建站1598013975310.png",
          source: "sync",
          tagVOS: [
            { sourceCode: null, pid: 235, tagId: 61, tagName: "架构图icon" },
            { sourceCode: null, pid: 235, tagId: 55, tagName: "2D" },
            { sourceCode: null, pid: 235, tagId: 61, tagName: "架构图icon" },
            { sourceCode: null, pid: 235, tagId: 62, tagName: "企业应用" },
            { sourceCode: null, pid: 235, tagId: 50, tagName: "图标" },
            { sourceCode: null, pid: 235, tagId: 59, tagName: "无人" },
          ],
          gmtCreate: "2020-08-21T12:45:56.000+0000",
          gmtModified: "2020-08-21T12:45:56.000+0000",
          creator: "5941",
          modifier: "5941",
          creatorName: "cxl",
          modifierName: "cxl",
          isDeleted: "n",
        },
        {
          id: 234,
          name: "ccs 云客服.png",
          url: "https://dayu-icon-prd.oss-cn-zhangjiakou.aliyuncs.com/icon/ccs 云客服1598013975221.png",
          source: "sync",
          tagVOS: [
            { sourceCode: null, pid: 234, tagId: 61, tagName: "架构图icon" },
            { sourceCode: null, pid: 234, tagId: 55, tagName: "2D" },
            { sourceCode: null, pid: 234, tagId: 61, tagName: "架构图icon" },
            { sourceCode: null, pid: 234, tagId: 62, tagName: "企业应用" },
            { sourceCode: null, pid: 234, tagId: 50, tagName: "图标" },
            { sourceCode: null, pid: 234, tagId: 59, tagName: "无人" },
          ],
          gmtCreate: "2020-08-21T12:45:56.000+0000",
          gmtModified: "2020-08-21T12:45:56.000+0000",
          creator: "5941",
          modifier: "5941",
          creatorName: "cxl",
          modifierName: "cxl",
          isDeleted: "n",
        },
      ],
    },
    traceId: "2f624a7616428309953098724e274a",
    empty: false,
  },
  "/design/metadata/get": {
    requestId: "914ee5e1-9e7d-4404-bd19-df09cbe01de6",
    code: "200",
    message: "success",
    success: true,
    meta: null,
    data: {
      id: 297,
      code: "openSourceTechnology-000001",
      cnName: null,
      enName: "React.js",
      firstCategoryId: 163,
      firstCategoryName: "开源技术体系",
      secondCategoryId: 43,
      secondCategoryName: "Web前端",
      thirdCategoryId: 44,
      thirdCategoryName: " 框架",
      shortDescription: "React.js",
      longDescription: "一个 UI 描述框架",
      introduction: " 前端最流行框架",
      gmtCreate: "2020-08-07T15:10:59.000+0000",
      gmtModified: "2020-08-07T15:10:59.000+0000",
      creator: "070186",
      modifier: "070186",
      creatorName: "华雷",
      modifierName: "华雷",
      isDeleted: "n",
      tagVOList: [],
      sortNum: 1,
      iconUrl:
        "https://img.alicdn.com/tfs/TB1mkHhgfzO3e4jSZFxXXaP_FXa-186-186.png",
      iconId: null,
      iconName: null,
      typeKey: "openSourceTechnology",
      typeValue: null,
      source: "local",
      officialWebsite: "https://reactjs.org/",
    },
    traceId: "2f624a7616428315656484518e274a",
    empty: false,
  },
  "/design/metadata/tree/get": {
    requestId: "df8cba30-6466-42a2-8732-a9b05b5cce50",
    code: "200",
    message: "success",
    success: true,
    meta: null,
    data: [
      {
        metadataId: 297,
        metadataName: "React.js",
        metadataSortNum: 1,
        metadataIconUrl:
          "https://img.alicdn.com/tfs/TB1mkHhgfzO3e4jSZFxXXaP_FXa-186-186.png",
        metadataOfficialWebsite: "https://reactjs.org/",
        source: "local",
        category1Id: 163,
        category1Name: "开源技术体系",
        category1SortNum: null,
        category2Id: 43,
        category2Name: "Web前端",
        category2SortNum: 1000,
        category3Id: 44,
        category3Name: " 框架",
        category3SortNum: null,
      },
    ],
    traceId: "2f624a7616428316743228713e274a",
    empty: false,
  },
  "/design/metadata/tag/search": {
    requestId: "3da9c2b5-bfd9-4c48-b4ff-2c69905c009d",
    code: "200",
    message: "success",
    success: true,
    meta: null,
    data: [
      {
        id: 210,
        code: "appstreaming",
        cnName: null,
        enName: "appstreaming",
        firstCategoryId: 162,
        firstCategoryName: "阿里云",
        secondCategoryId: 81,
        secondCategoryName: "企业应用",
        thirdCategoryId: null,
        thirdCategoryName: null,
        shortDescription: "无影",
        longDescription: null,
        introduction: null,
        gmtCreate: "2020-08-07T13:50:17.000+0000",
        gmtModified: "2022-01-21T09:00:01.000+0000",
        creator: null,
        modifier: null,
        creatorName: null,
        modifierName: null,
        isDeleted: "n",
        sortNum: null,
        iconUrl: null,
        iconId: null,
        iconName: null,
        typeKey: "aliyun",
        typeValue: null,
        tagVOList: null,
        source: "cloud",
        officialWebsite: null,
      },
      {
        id: 297,
        code: "openSourceTechnology-000001",
        cnName: null,
        enName: "React.js",
        firstCategoryId: 163,
        firstCategoryName: "开源技术体系",
        secondCategoryId: 43,
        secondCategoryName: "Web前端",
        thirdCategoryId: 44,
        thirdCategoryName: " 框架",
        shortDescription: "React.js",
        longDescription: "一个 UI 描述框架",
        introduction: " 前端最流行框架",
        gmtCreate: "2020-08-07T15:10:59.000+0000",
        gmtModified: "2020-08-07T15:10:59.000+0000",
        creator: "070186",
        modifier: "070186",
        creatorName: "华雷",
        modifierName: "华雷",
        isDeleted: "n",
        sortNum: 1,
        iconUrl:
          "https://img.alicdn.com/tfs/TB1mkHhgfzO3e4jSZFxXXaP_FXa-186-186.png",
        iconId: null,
        iconName: null,
        typeKey: "openSourceTechnology",
        typeValue: null,
        tagVOList: null,
        source: "local",
        officialWebsite: "https://reactjs.org/",
      },
      {
        id: 479,
        code: "mpincrease",
        cnName: null,
        enName: "intelligence increase",
        firstCategoryId: 162,
        firstCategoryName: "阿里云",
        secondCategoryId: null,
        secondCategoryName: null,
        thirdCategoryId: null,
        thirdCategoryName: null,
        shortDescription: "智能拉新",
        longDescription: null,
        introduction: null,
        gmtCreate: "2020-10-12T09:00:00.000+0000",
        gmtModified: "2022-01-21T09:00:01.000+0000",
        creator: null,
        modifier: null,
        creatorName: null,
        modifierName: null,
        isDeleted: "n",
        sortNum: null,
        iconUrl: null,
        iconId: null,
        iconName: null,
        typeKey: "aliyun",
        typeValue: null,
        tagVOList: null,
        source: "cloud",
        officialWebsite: null,
      },
    ],
    traceId: "2f624a7616428320460927708e274a",
    empty: false,
  },
  "POST /design/metadata/list/delete": postRes,
  "POST /design/metadata/add": postRes,
  "PUT /design/metadata/update": postRes,
  "POST /project/api/project/instance/related": postRes,
  "POST /design/instance/insert": {
    requestId: "a5198169-9716-42c8-b75c-12c7408e6227",
    code: "200",
    message: "success",
    success: true,
    meta: null,
    data: { id: 8066 },
    traceId: "2f624a7616428322695876830e2740",
    empty: false,
  },
  "PUT /design/instance/update": postRes,
  "PUT /design/template/update": postRes,
  "POST /design/instance/delete": postRes,
  "POST /design/template/delete": postRes,
  "POST /design/template/insert": postRes,
  "POST /design/template/name/get": postRes,
  "PUT /design/instance/after/update": postRes,
  "POST /design/instance/open/update": postRes,
  "POST /design/template/open/update": postRes,
  "POST /design/tag/relation/update": postRes,
  "POST /design/icon/add": postRes,
  "POST /design/icon/update": postRes,
  "/design/template/check/list": {
    requestId: "36e2a5a7-b7a9-4808-a0cf-addc86e24adf",
    code: "200",
    message: "success",
    success: true,
    meta: null,
    data: [
      {
        id: 16,
        fileString: null,
        name: "西安最多跑一次",
        description: null,
        gmtCreate: "2021-03-22T06:37:12.000+0000",
        gmtModified: "2021-03-22T06:37:12.000+0000",
        creator: "WB796162",
        modifier: "WB796162",
        creatorName: "孙鹏",
        modifierName: "孙鹏",
        isDeleted: "n",
        xmlText:
          '<mxgraphmodel><root width="1419" height="836"></root></mxgraphmodel>',
        xml: '<mxGraphModel><root><mxCell id="0" value="技术架构图"/><mxCell id="1" value="默认图层" parent="0"/></root></mxGraphModel>',
        version: 1,
        fileKey: "file/design/xxx.txt",
        typeKey: "fast",
        typeName: "快速架构图",
        open: null,
        status: "inReview",
        tagVOList: null,
        own: null,
        tagNames: null,
        totalPv: null,
      },
    ],
    traceId: "2f624a7616428309953503929e2744",
    empty: false,
  },

  // "POST /api/users/create": (req, res) => {
  //   // 添加跨域请求头
  //   res.setHeader("Access-Control-Allow-Origin", "*");
  //   res.end("ok");
  // },
};
