
# 运行 brew bundle
# https://catalins.tech/how-i-setup-new-macbooks/

brew "git"
brew "node"
brew "ffmpeg"
brew "cask"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"

# 自动安装到 /Applications 目录里
cask "google-chrome"
cask "postman"
cask "cursor"
cask "discord"
cask "raycast"
cask "whatsapp"
cask "warp"
cask "cleanshot"
cask "docker"
cask "vlc"
