#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WebFileDB")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  partial void InsertFile(File instance);
  partial void UpdateFile(File instance);
  partial void DeleteFile(File instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["WebFileDBConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<File> File
	{
		get
		{
			return this.GetTable<File>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Pr_AddFile")]
	public int Pr_AddFile([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Desn", DbType="VarChar(200)")] string desn, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Url", DbType="VarChar(500)")] string url, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsDir", DbType="Int")] System.Nullable<int> isDir, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParentID", DbType="Int")] System.Nullable<int> parentID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), desn, url, isDir, parentID);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Pr_DeleteFile")]
	public int Pr_DeleteFile([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FileID", DbType="Int")] System.Nullable<int> fileID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fileID);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Pr_GetFiles")]
	public ISingleResult<Pr_GetFilesResult> Pr_GetFiles()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<Pr_GetFilesResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Pr_GetSingleFile")]
	public ISingleResult<Pr_GetSingleFileResult> Pr_GetSingleFile([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FileID", DbType="Int")] System.Nullable<int> fileID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fileID);
		return ((ISingleResult<Pr_GetSingleFileResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Pr_UpdateFile")]
	public int Pr_UpdateFile([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FileID", DbType="Int")] System.Nullable<int> fileID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Desn", DbType="VarChar(200)")] string desn)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fileID, desn);
		return ((int)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[File]")]
public partial class File : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _FileID;
	
	private string _Desn;
	
	private string _Url;
	
	private System.Nullable<int> _IsDir;
	
	private System.Nullable<int> _ParentID;
	
	private System.Nullable<System.DateTime> _CreateDate;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFileIDChanging(int value);
    partial void OnFileIDChanged();
    partial void OnDesnChanging(string value);
    partial void OnDesnChanged();
    partial void OnUrlChanging(string value);
    partial void OnUrlChanged();
    partial void OnIsDirChanging(System.Nullable<int> value);
    partial void OnIsDirChanged();
    partial void OnParentIDChanging(System.Nullable<int> value);
    partial void OnParentIDChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    #endregion
	
	public File()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int FileID
	{
		get
		{
			return this._FileID;
		}
		set
		{
			if ((this._FileID != value))
			{
				this.OnFileIDChanging(value);
				this.SendPropertyChanging();
				this._FileID = value;
				this.SendPropertyChanged("FileID");
				this.OnFileIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Desn", DbType="VarChar(200)")]
	public string Desn
	{
		get
		{
			return this._Desn;
		}
		set
		{
			if ((this._Desn != value))
			{
				this.OnDesnChanging(value);
				this.SendPropertyChanging();
				this._Desn = value;
				this.SendPropertyChanged("Desn");
				this.OnDesnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="VarChar(500)")]
	public string Url
	{
		get
		{
			return this._Url;
		}
		set
		{
			if ((this._Url != value))
			{
				this.OnUrlChanging(value);
				this.SendPropertyChanging();
				this._Url = value;
				this.SendPropertyChanged("Url");
				this.OnUrlChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDir", DbType="Int")]
	public System.Nullable<int> IsDir
	{
		get
		{
			return this._IsDir;
		}
		set
		{
			if ((this._IsDir != value))
			{
				this.OnIsDirChanging(value);
				this.SendPropertyChanging();
				this._IsDir = value;
				this.SendPropertyChanged("IsDir");
				this.OnIsDirChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID", DbType="Int")]
	public System.Nullable<int> ParentID
	{
		get
		{
			return this._ParentID;
		}
		set
		{
			if ((this._ParentID != value))
			{
				this.OnParentIDChanging(value);
				this.SendPropertyChanging();
				this._ParentID = value;
				this.SendPropertyChanged("ParentID");
				this.OnParentIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

public partial class Pr_GetFilesResult
{
	
	private int _FileID;
	
	private string _Desn;
	
	private string _Url;
	
	private System.Nullable<int> _IsDir;
	
	private System.Nullable<int> _ParentID;
	
	private System.Nullable<System.DateTime> _CreateDate;
	
	public Pr_GetFilesResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileID", DbType="Int NOT NULL")]
	public int FileID
	{
		get
		{
			return this._FileID;
		}
		set
		{
			if ((this._FileID != value))
			{
				this._FileID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Desn", DbType="VarChar(200)")]
	public string Desn
	{
		get
		{
			return this._Desn;
		}
		set
		{
			if ((this._Desn != value))
			{
				this._Desn = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="VarChar(500)")]
	public string Url
	{
		get
		{
			return this._Url;
		}
		set
		{
			if ((this._Url != value))
			{
				this._Url = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDir", DbType="Int")]
	public System.Nullable<int> IsDir
	{
		get
		{
			return this._IsDir;
		}
		set
		{
			if ((this._IsDir != value))
			{
				this._IsDir = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID", DbType="Int")]
	public System.Nullable<int> ParentID
	{
		get
		{
			return this._ParentID;
		}
		set
		{
			if ((this._ParentID != value))
			{
				this._ParentID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this._CreateDate = value;
			}
		}
	}
}

public partial class Pr_GetSingleFileResult
{
	
	private int _FileID;
	
	private string _Desn;
	
	private string _Url;
	
	private System.Nullable<int> _IsDir;
	
	private System.Nullable<int> _ParentID;
	
	private System.Nullable<System.DateTime> _CreateDate;
	
	public Pr_GetSingleFileResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileID", DbType="Int NOT NULL")]
	public int FileID
	{
		get
		{
			return this._FileID;
		}
		set
		{
			if ((this._FileID != value))
			{
				this._FileID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Desn", DbType="VarChar(200)")]
	public string Desn
	{
		get
		{
			return this._Desn;
		}
		set
		{
			if ((this._Desn != value))
			{
				this._Desn = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="VarChar(500)")]
	public string Url
	{
		get
		{
			return this._Url;
		}
		set
		{
			if ((this._Url != value))
			{
				this._Url = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDir", DbType="Int")]
	public System.Nullable<int> IsDir
	{
		get
		{
			return this._IsDir;
		}
		set
		{
			if ((this._IsDir != value))
			{
				this._IsDir = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID", DbType="Int")]
	public System.Nullable<int> ParentID
	{
		get
		{
			return this._ParentID;
		}
		set
		{
			if ((this._ParentID != value))
			{
				this._ParentID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this._CreateDate = value;
			}
		}
	}
}
#pragma warning restore 1591
