<?xml version="1.0" encoding="utf-8"?><Database Name="WebFileDB" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=HUA-PC;Initial Catalog=WebFileDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="WebFileDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[File]" Member="File">
    <Type Name="File">
      <Column Name="FileID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Desn" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="IsDir" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.Pr_AddFile" Method="Pr_AddFile">
    <Parameter Name="Desn" Parameter="desn" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Url" Parameter="url" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="IsDir" Parameter="isDir" Type="System.Int32" DbType="Int" />
    <Parameter Name="ParentID" Parameter="parentID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Pr_DeleteFile" Method="Pr_DeleteFile">
    <Parameter Name="FileID" Parameter="fileID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Pr_GetFiles" Method="Pr_GetFiles">
    <ElementType Name="Pr_GetFilesResult">
      <Column Name="FileID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Desn" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="IsDir" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Pr_GetSingleFile" Method="Pr_GetSingleFile">
    <Parameter Name="FileID" Parameter="fileID" Type="System.Int32" DbType="Int" />
    <ElementType Name="Pr_GetSingleFileResult">
      <Column Name="FileID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Desn" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="IsDir" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Pr_UpdateFile" Method="Pr_UpdateFile">
    <Parameter Name="FileID" Parameter="fileID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Desn" Parameter="desn" Type="System.String" DbType="VarChar(200)" />
    <Return Type="System.Int32" />
  </Function>
</Database>